- name: Install required packages
  apt:
    name:
      - apache2
      - php
      - php-pgsql
      - php-xml
      - php-curl
      - composer
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Verify PHP extensions are installed
  command: php -m
  register: php_extensions
  failed_when: "'dom' not in php_extensions.stdout or 'xml' not in php_extensions.stdout or 'curl' not in php_extensions.stdout"

- name: Create Laravel system user
  user:
    name: laravel
    home: /var/www/html/app-for-devops
    shell: /bin/bash

- name: Set ownership of Laravel app
  file:
    path: /var/www/html/app-for-devops
    owner: laravel
    group: www-data
    recurse: yes

- name: Set permissions for Laravel app
  file:
    path: /var/www/html/app-for-devops
    state: directory
    mode: '0775'
    recurse: yes

- name: Clone Laravel application
  git:
    repo: "https://github.com/Practical-DevOps/app-for-devops"
    dest: /var/www/html/app-for-devops
    force: yes
    update: yes

- name: Set database configuration
  template:
    src: db.env.j2
    dest: /var/www/html/app-for-devops/.env

- name: Update PHP dependencies
  become: yes
  become_user: laravel
  command: composer update
  args:
    chdir: /var/www/html/app-for-devops

- name: Install PHP dependencies
  become: yes
  become_user: laravel
  command: composer install
  args:
    chdir: /var/www/html/app-for-devops

- name: Generate application key
  become: yes
  become_user: laravel
  command: php artisan key:generate
  args:
    chdir: /var/www/html/app-for-devops

- name: Run database migrations
  become: yes
  become_user: laravel
  command: php artisan migrate
  args:
    chdir: /var/www/html/app-for-devops

- name: Install NPM dependencies
  become: yes
  become_user: laravel
  command: npm install
  args:
    chdir: /var/www/html/app-for-devops

- name: Build frontend assets
  become: yes
  become_user: laravel
  command: npm run build
  args:
    chdir: /var/www/html/app-for-devops

- name: Set permissions for Laravel
  file:
    path: /var/www/html/app-for-devops
    state: directory
    mode: '0775'
    recurse: yes

- name: Enable Apache rewrite module
  command: a2enmod rewrite

- name: Restart Apache
  service:
    name: apache2
    state: restarted
