- name: Clone Laravel application
  git:
    repo: "https://github.com/Practical-DevOps/app-for-devops"
    dest: /var/www/html/app-for-devops
    update: yes

- name: Remove conflicting Node.js packages
  apt:
    name:
      - nodejs
      - libnode-dev
    state: absent
    purge: yes
    autoremove: yes

- name: Clean up residual Node.js files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/lib/node_modules
    - /usr/include/node
    - /usr/local/lib/node_modules

- name: Add NodeSource repository for Node.js 20.x
  shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  args:
    executable: /bin/bash

- name: Install Node.js
  apt:
    name: nodejs
    state: latest

- name: Verify Node.js installation
  command: node -v
  register: node_version
  changed_when: false
  failed_when: '"v20" not in node_version.stdout'

- name: Install required packages
  apt:
    name:
      - apache2
      - php
      - php-pgsql
      - php-xml
      - php-curl
      - composer
    state: present
    update_cache: yes

- name: Verify PHP extensions are installed
  command: php -m
  register: php_extensions
  failed_when: "'dom' not in php_extensions.stdout or 'xml' not in php_extensions.stdout or 'curl' not in php_extensions.stdout"

- name: Create Laravel system user
  user:
    name: laravel
    home: /var/www/html/app-for-devops
    shell: /bin/bash
    state: present

- name: Set ownership of Laravel app
  file:
    path: /var/www/html/app-for-devops
    owner: laravel
    group: www-data
    recurse: yes

- name: Set permissions for Laravel app
  file:
    path: /var/www/html/app-for-devops
    state: directory
    mode: '0775'
    recurse: yes

- name: Create .env file from template
  template:
    src: db.env.j2
    dest: /var/www/html/app-for-devops/.env
    owner: laravel
    group: www-data
    mode: '0664'

- name: Ensure .env file is writable
  file:
    path: /var/www/html/app-for-devops/.env
    mode: '0664'
    owner: laravel
    group: www-data

- name: Update PHP dependencies
  become: yes
  become_user: laravel
  command: composer update
  args:
    chdir: /var/www/html/app-for-devops

- name: Install PHP dependencies
  become: yes
  become_user: laravel
  command: composer install --no-dev
  args:
    chdir: /var/www/html/app-for-devops

- name: Generate application key
  become: yes
  become_user: laravel
  command: php artisan key:generate
  args:
    chdir: /var/www/html/app-for-devops

- name: Run database migrations
  become: yes
  become_user: laravel
  command: php artisan migrate --force --no-interaction
  args:
    chdir: /var/www/html/app-for-devops

- name: Clean up existing node_modules (if any)
  file:
    path: /var/www/html/app-for-devops/node_modules
    state: absent

- name: Install NPM dependencies
  become: yes
  become_user: laravel
  command: npm install
  args:
    chdir: /var/www/html/app-for-devops

- name: Build frontend assets
  become: yes
  become_user: laravel
  command: npm run build
  args:
    chdir: /var/www/html/app-for-devops

- name: Enable Apache rewrite module
  command: a2enmod rewrite
  args:
    creates: /etc/apache2/mods-enabled/rewrite.load

- name: Create Apache virtual host for Laravel
  copy:
    dest: /etc/apache2/sites-available/laravel.conf
    content: |
      <VirtualHost *:80>
          ServerName laravel-app
          DocumentRoot /var/www/html/app-for-devops/public

          <Directory /var/www/html/app-for-devops/public>
              AllowOverride All
              Require all granted
          </Directory>

          ErrorLog ${APACHE_LOG_DIR}/laravel-error.log
          CustomLog ${APACHE_LOG_DIR}/laravel-access.log combined
      </VirtualHost>

- name: Enable Apache site for Laravel
  command: a2ensite laravel.conf

- name: Restart Apache
  service:
    name: apache2
    state: restarted
