---
- name: Install required Python libraries
  apt:
    name:
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ pg_version }}"
    state: present
    update_cache: yes

- name: Install PostgreSQL client tools
  apt:
    name: "postgresql-client-{{ pg_version }}"
    state: present
    update_cache: yes

- name: Ensure PostgreSQL server is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure password for postgres user is set
  block:
    - name: Check if postgres user password is already set
      shell: |
        psql -U postgres -d postgres -c "SELECT 1" >/dev/null 2>&1 && echo "OK" || echo "FAIL"
      become: yes
      become_user: postgres
      register: postgres_password_status
      changed_when: false
      failed_when: false

    - name: Set password for postgres user if not set
      postgresql_user:
        name: postgres
        password: "{{ db_pass }}"
        state: present
      when: postgres_password_status.stdout != "OK"

- name: Ensure PostgreSQL uses md5 authentication for postgres user
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    regexp: '^local\s+all\s+postgres\s+peer$'
    line: 'local   all             postgres                                md5'
    state: present
  register: auth_config_updated

- name: Allow remote connections in pg_hba.conf
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    insertafter: '^# IPv4 local connections:'
    line: "host    all             all             0.0.0.0/0               md5"
    state: present
  register: remote_config_updated

- name: Allow PostgreSQL to listen on all IPs
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    regexp: '^#listen_addresses ='
    line: "listen_addresses = '*'"
    state: present
  register: listen_config_updated

- name: Restart PostgreSQL service if configuration updated
  service:
    name: postgresql
    state: restarted
  when:
    - auth_config_updated.changed
    - remote_config_updated.changed
    - listen_config_updated.changed