- name: Ensure required Python libraries are installed
  apt:
    name:
      - python3-psycopg2
      - python3-pip
    state: present
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present

- name: Create database user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present

- name: Grant privileges on database
  postgresql_privs:
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    type: "database"
    privs: "ALL"
