- name: Install required Python libraries
  apt:
    name:
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ pg_version }}"
    state: present
    update_cache: yes

- name: Install PostgreSQL client tools
  apt:
    name: "postgresql-client-{{ pg_version }}"
    state: present
    update_cache: yes

- name: Ensure PostgreSQL server is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Set password for postgres user
  become: yes
  become_user: postgres
  command: psql -c "ALTER USER postgres PASSWORD '{{ db_pass }}';"

- name: Ensure PostgreSQL uses md5 authentication for postgres user
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    regexp: '^local\s+all\s+postgres\s+peer$'
    line: 'local   all             postgres                                md5'
    state: present

- name: Restart PostgreSQL service
  service:
    name: postgresql
    state: restarted