# - name: Setup Web Server
#   hosts: server
#   roles:
#     - server
#   vars:
#     db_host: "{{ db_host }}"
#     db_name: "{{ db_name }}"
#     db_user: "{{ db_user }}"
#     db_pass: "{{ db_pass }}"

- name: Setup Database Server
  hosts: db
  roles:
    - db
  vars:
    db_name: "{{ db_name }}"
    db_user: "{{ db_user }}"
    db_pass: "{{ db_pass }}"
